font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

cursor_shape beam

background_blur 5
background_opacity 0.7

foreground   #ebdfe2
background   #1f1a1c
cursor       #ebdfe2


