# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

source = $HOME/.config/hypr/config/monitors.conf
source = $HOME/.config/hypr/config/variables.conf
source = $HOME/.config/hypr/config/autostart.conf
source = $HOME/.config/hypr/config/environment.conf
source = $HOME/.config/hypr/config/permissions.conf
source = $HOME/.config/hypr/config/appearance.conf
source = $HOME/.config/hypr/config/workspace-rules.conf
source = $HOME/.config/hypr/config/permissions.conf
source = $HOME/.config/hypr/config/appearance.conf
source = $HOME/.config/hypr/config/input.conf
source = $HOME/.config/hypr/config/keybinds.conf
source = $HOME/.config/hypr/config/windows.conf







